# Generated by Django 5.2.17 on 2026-08-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absence',
            options={'ordering': ['-start_datetime'], 'verbose_name': 'absence', 'verbose_name_plural': 'absences'},
        ),
        migrations.AlterModelOptions(
            name='substitution',
            options={'verbose_name': 'substitution', 'verbose_name_plural': 'substitutions'},
        ),
        migrations.AlterField(
            model_name='absence',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='end_datetime',
            field=models.DateTimeField(verbose_name='unavailable until'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='reason'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='start_datetime',
            field=models.DateTimeField(verbose_name='unavailable from'),
        ),
        migrations.AlterField(
            model_name='substitution',
            name='confirmed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='confirmed at'),
        ),
    ]
