# Generated by Django 5.2.17 on 2026-08-18 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitutions', '0003_split_substitutions'),
        ('teachers', '0003_alter_teacher_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubstitutionOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='offered from')),
                ('end_datetime', models.DateTimeField(verbose_name='offered until')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=10, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='offered at')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='responded at')),
                ('absence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='substitutions.absence')),
                ('resulting_substitution', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer', to='substitutions.substitution', verbose_name='resulting substitution')),
                ('substitute_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitution_offers', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'substitution offer',
                'verbose_name_plural': 'substitution offers',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_datetime__gt', models.F('start_datetime'))), name='substitution_offer_end_after_start'), models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('absence', 'substitute_teacher', 'start_datetime', 'end_datetime'), name='unique_pending_offer_per_candidate_slot')],
            },
        ),
    ]
