# Generated by Django 5.2.17 on 2026-08-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitutions', '0004_substitutionoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='reason',
            field=models.CharField(blank=True, choices=[('baixa_it_at', 'Baixa IT-AT'), ('permisos', 'Permisos'), ('activitat_escola', 'Activitat Escola'), ('activitat_fundacio', 'Activitat Fundació')], max_length=255, verbose_name='reason'),
        ),
    ]
