# Generated by Django 5.2.17 on 2026-08-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitutions', '0006_alter_absence_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='substitutionoffer',
            name='decline_reason',
            field=models.CharField(blank=True, choices=[('interview', 'Interview'), ('meeting', 'Meeting'), ('personal', 'Personal reasons'), ('other', 'Other')], max_length=20, verbose_name='decline reason'),
        ),
        migrations.AddField(
            model_name='substitutionoffer',
            name='decline_reason_detail',
            field=models.CharField(blank=True, max_length=255, verbose_name='decline reason detail'),
        ),
    ]
