# Generated by Django 5.2.17 on 2026-08-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklynonteachinghours',
            name='is_paperwork',
            field=models.BooleanField(default=False, help_text='Reserved for paperwork/admin work, as opposed to fully free time.'),
        ),
    ]
