# Generated by Django 5.2.17 on 2026-08-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_weeklynonteachinghours_is_paperwork'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['user__last_name', 'user__first_name'], 'verbose_name': 'teacher', 'verbose_name_plural': 'teachers'},
        ),
        migrations.AlterModelOptions(
            name='weeklynonteachinghours',
            options={'ordering': ['weekday', 'start_time'], 'verbose_name': 'weekly non-teaching hours', 'verbose_name_plural': 'weekly non-teaching hours'},
        ),
        migrations.AlterField(
            model_name='teacher',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='grade_level',
            field=models.CharField(choices=[('primary', 'Primary'), ('pre_primary', 'Pre-primary')], max_length=20, verbose_name='grade level'),
        ),
        migrations.AlterField(
            model_name='weeklynonteachinghours',
            name='end_time',
            field=models.TimeField(verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='weeklynonteachinghours',
            name='is_paperwork',
            field=models.BooleanField(default=False, help_text='Reserved for paperwork/admin work, as opposed to fully free time.', verbose_name='paperwork'),
        ),
        migrations.AlterField(
            model_name='weeklynonteachinghours',
            name='start_time',
            field=models.TimeField(verbose_name='start time'),
        ),
        migrations.AlterField(
            model_name='weeklynonteachinghours',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='weekday'),
        ),
    ]
