# Generated by Django 5.2.17 on 2026-09-02 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_non_teaching_hours_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklynonteachinghours',
            name='head',
            field=models.ForeignKey(blank=True, help_text='The teacher who leads this co-taught class. Required for co-teaching blocks.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_teaching_led', to='teachers.teacher', verbose_name='co-teaching head'),
        ),
        migrations.AddConstraint(
            model_name='weeklynonteachinghours',
            constraint=models.CheckConstraint(condition=models.Q(('head', models.F('teacher')), _negated=True), name='co_teaching_head_is_not_self'),
        ),
    ]
