# Generated by Django 5.2.17 on 2026-09-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_weeklynonteachinghours_head_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='calendar_url',
            field=models.URLField(blank=True, help_text="Link to this teacher's calendar. Shown when relevant if set.", verbose_name='calendar link'),
        ),
    ]
