# Generated by Django 5.2.17 on 2026-09-18 20:03

from django.db import migrations, models

# Seeded after escoltam (see 0004_non_teaching_hours_kind) - same gaps-of-10
# convention, added at the end so existing priorities are left untouched.
NEW_PRIORITIES = [
    ("poesia", 40),
    ("cicle", 50),
]


def seed_priorities(apps, schema_editor):
    NonTeachingHoursPriority = apps.get_model("teachers", "NonTeachingHoursPriority")
    NonTeachingHoursPriority.objects.bulk_create(
        [NonTeachingHoursPriority(kind=kind, priority=priority) for kind, priority in NEW_PRIORITIES]
    )


def undo(apps, schema_editor):
    NonTeachingHoursPriority = apps.get_model("teachers", "NonTeachingHoursPriority")
    NonTeachingHoursPriority.objects.filter(kind__in=[kind for kind, _priority in NEW_PRIORITIES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_teacher_calendar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonteachinghourspriority',
            name='kind',
            field=models.CharField(choices=[('free', 'Free'), ('paperwork', 'Paperwork'), ('co_teaching', 'Co-teaching'), ('escoltam', "Escolta'm"), ('poesia', 'POESIA'), ('cicle', 'Cicle')], max_length=20, unique=True, verbose_name='kind'),
        ),
        migrations.AlterField(
            model_name='weeklynonteachinghours',
            name='kind',
            field=models.CharField(choices=[('free', 'Free'), ('paperwork', 'Paperwork'), ('co_teaching', 'Co-teaching'), ('escoltam', "Escolta'm"), ('poesia', 'POESIA'), ('cicle', 'Cicle')], default='free', max_length=20, verbose_name='kind'),
        ),
        migrations.RunPython(seed_priorities, undo),
    ]
