# Generated by Django 5.2.17 on 2026-09-20 13:57

import django.db.models.deletion
import schools.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('teachers', '0007_add_poesia_and_cicle_non_teaching_kinds'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonteachinghourspriority',
            name='school',
            field=models.ForeignKey(default=schools.models.get_default_school_id, on_delete=django.db.models.deletion.CASCADE, related_name='non_teaching_hours_priorities', to='schools.school', verbose_name='school'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('member', 'Member')], default='member', help_text="Staff can manage this school's roster and timetable.", max_length=10, verbose_name='role'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(default=schools.models.get_default_school_id, on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='schools.school', verbose_name='school'),
        ),
        migrations.AlterField(
            model_name='nonteachinghourspriority',
            name='kind',
            field=models.CharField(choices=[('free', 'Free'), ('paperwork', 'Paperwork'), ('co_teaching', 'Co-teaching'), ('escoltam', "Escolta'm"), ('poesia', 'POESIA'), ('cicle', 'Cicle')], max_length=20, verbose_name='kind'),
        ),
        migrations.AddConstraint(
            model_name='nonteachinghourspriority',
            constraint=models.UniqueConstraint(fields=('school', 'kind'), name='unique_priority_per_school_kind'),
        ),
    ]
