# Generated by Django 5.2.17 on 2026-09-24 08:18

from django.db import migrations, models

# Seeded after cicle (see 0007_add_poesia_and_cicle_non_teaching_kinds) - same
# gaps-of-10 convention. NonTeachingHoursPriority is now per-school (see
# 0008_nonteachinghourspriority_school_teacher_role_and_more), so unlike 0007
# this has to seed one row per existing school rather than one bare row.
NEW_KIND = "reforc"
NEW_PRIORITY = 60


def seed_priorities(apps, schema_editor):
    School = apps.get_model("schools", "School")
    NonTeachingHoursPriority = apps.get_model("teachers", "NonTeachingHoursPriority")
    NonTeachingHoursPriority.objects.bulk_create(
        [NonTeachingHoursPriority(school=school, kind=NEW_KIND, priority=NEW_PRIORITY) for school in School.objects.all()]
    )


def undo(apps, schema_editor):
    NonTeachingHoursPriority = apps.get_model("teachers", "NonTeachingHoursPriority")
    NonTeachingHoursPriority.objects.filter(kind=NEW_KIND).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_backfill_staff_role'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonteachinghourspriority',
            name='kind',
            field=models.CharField(choices=[('free', 'Free'), ('paperwork', 'Paperwork'), ('co_teaching', 'Co-teaching'), ('escoltam', "Escolta'm"), ('poesia', 'POESIA'), ('cicle', 'Cicle'), ('reforc', 'Reforç')], max_length=20, verbose_name='kind'),
        ),
        migrations.AlterField(
            model_name='weeklynonteachinghours',
            name='kind',
            field=models.CharField(choices=[('free', 'Free'), ('paperwork', 'Paperwork'), ('co_teaching', 'Co-teaching'), ('escoltam', "Escolta'm"), ('poesia', 'POESIA'), ('cicle', 'Cicle'), ('reforc', 'Reforç')], default='free', max_length=20, verbose_name='kind'),
        ),
        migrations.RunPython(seed_priorities, undo),
    ]
