# Generated by Django 5.2.17 on 2026-09-24 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0010_add_reforc_non_teaching_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklynonteachinghours',
            name='head',
            field=models.ForeignKey(blank=True, help_text='The teacher this block is with. Required for co-teaching and Reforç blocks.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_teaching_led', to='teachers.teacher', verbose_name='head teacher'),
        ),
    ]
