# Generated by Django 5.2.17 on 2026-09-15 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0006_teacher_calendar_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'subject',
                'verbose_name_plural': 'subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('grade_level', models.CharField(choices=[('primary', 'Primary'), ('pre_primary', 'Pre-primary')], max_length=20, verbose_name='grade level')),
                ('tutor', models.ForeignKey(help_text="The homeroom teacher, who usually teaches most of this group's subjects.", on_delete=django.db.models.deletion.PROTECT, related_name='tutored_groups', to='teachers.teacher', verbose_name='tutor')),
            ],
            options={
                'verbose_name': 'class group',
                'verbose_name_plural': 'class groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='weekday')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='schedule.classgroup')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='teachers.teacher')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_entries', to='schedule.subject')),
            ],
            options={
                'verbose_name': 'schedule entry',
                'verbose_name_plural': 'schedule entries',
                'ordering': ['weekday', 'start_time'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='schedule_entry_end_after_start')],
            },
        ),
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualified_teachers', to='schedule.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects_taught', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'teacher expertise',
                'verbose_name_plural': 'teacher expertise',
                'ordering': ['subject__name'],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'subject'), name='unique_teacher_subject')],
            },
        ),
    ]
