# Generated by Django 5.2.17 on 2026-09-16 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        ('teachers', '0006_teacher_calendar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleentry',
            name='co_teacher',
            field=models.ForeignKey(blank=True, help_text='A second teacher who also teaches this class alongside the main one, if any.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_taught_schedule_entries', to='teachers.teacher', verbose_name='co-teacher'),
        ),
    ]
