# Generated by Django 5.2.17 on 2026-09-17 06:57

import django.core.validators
from django.db import migrations, models


def copy_tutor_and_co_teacher_to_m2m(apps, schema_editor):
    ClassGroup = apps.get_model("schedule", "ClassGroup")
    ScheduleEntry = apps.get_model("schedule", "ScheduleEntry")

    for group in ClassGroup.objects.all():
        group.tutors.add(group.tutor_id)
    for entry in ScheduleEntry.objects.exclude(co_teacher__isnull=True):
        entry.co_teachers.add(entry.co_teacher_id)


def noop_reverse(apps, schema_editor):
    """The old FK fields are gone by the time this migration would be
    unapplied, so there's nothing to copy back into them."""


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_scheduleentry_co_teacher'),
        ('teachers', '0006_teacher_calendar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='classgroup',
            name='tutor_count',
            field=models.PositiveSmallIntegerField(default=1, help_text="How many tutor dropdowns to show when editing this group's tutors below.", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='number of tutors'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='tutors',
            field=models.ManyToManyField(blank=True, help_text="The homeroom teacher(s), who usually teach most of this group's subjects.", related_name='tutored_groups', to='teachers.teacher', verbose_name='tutors'),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='co_teachers',
            field=models.ManyToManyField(blank=True, help_text='Other teacher(s) who also teach this class alongside the main one, if any.', related_name='co_taught_schedule_entries', to='teachers.teacher', verbose_name='co-teachers'),
        ),
        migrations.RunPython(copy_tutor_and_co_teacher_to_m2m, noop_reverse),
        migrations.RemoveField(
            model_name='classgroup',
            name='tutor',
        ),
        migrations.RemoveField(
            model_name='scheduleentry',
            name='co_teacher',
        ),
    ]
