# Generated by Django 5.2.17 on 2026-09-20 13:57

import django.db.models.deletion
import schools.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_multi_tutors_and_co_teachers'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classgroup',
            name='school',
            field=models.ForeignKey(default=schools.models.get_default_school_id, on_delete=django.db.models.deletion.PROTECT, related_name='class_groups', to='schools.school', verbose_name='school'),
        ),
        migrations.AddField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(default=schools.models.get_default_school_id, on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='schools.school', verbose_name='school'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_subject_name_per_school'),
        ),
    ]
