# Generated by Django 5.2.17 on 2026-09-20 13:57

import schools.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('subdomain', models.SlugField(blank=True, help_text='Leave blank for the school served at the bare base domain.', null=True, unique=True, verbose_name='subdomain')),
                ('timezone', models.CharField(default='Europe/Madrid', max_length=64, verbose_name='timezone')),
                ('school_year_start_month', models.PositiveSmallIntegerField(default=9, verbose_name='school year start month')),
                ('school_year_start_day', models.PositiveSmallIntegerField(default=1, verbose_name='school year start day')),
                ('working_weekdays', models.JSONField(default=schools.models.default_working_weekdays, help_text='Weekdays the school runs classes, Monday=0 ... Sunday=6.', verbose_name='working weekdays')),
                ('working_hours', models.JSONField(default=schools.models.default_working_hours, help_text='Daily windows substitutes may be searched in, e.g. [["09:00", "13:00"]].', verbose_name='working hours')),
                ('display_color', models.CharField(blank=True, max_length=7, verbose_name='display color')),
            ],
            options={
                'verbose_name': 'school',
                'verbose_name_plural': 'schools',
                'ordering': ['name'],
            },
        ),
    ]
